library(tidyverse)
library(ggbeeswarm)
library(patchwork)
requireNamespace("ggbreak", quietly = TRUE)
requireNamespace("cowplot", quietly = TRUE)
requireNamespace("ggrepel", quietly = TRUE)
requireNamespace("forcats", quietly = TRUE)

# data files are generated by running 'Rscript scripts/figure1a_generate_data.R'

# read data
benchmarks <- yaml::read_yaml("data/fig1a_benchmarks.yaml")
method_info <- as_tibble(yaml::read_yaml("data/fig1a_method_info.yaml")) %>%
  mutate(date = ymd(date))
benchmark_commits <- as_tibble(read.delim("data/fig1a_benchmark_commits.tsv", sep = "\t")) %>%
  mutate(date = ymd_hms(date))

# create data frames
names <- sort(map_chr(benchmarks, "name"))
methods <- sort(unique(unlist(map(benchmarks, "methods"))))
metrics <- sort(unique(unlist(map(benchmarks, "metrics"))))
palette <- c("0" = "white", "1" = "#999999", "2" = "#222222")

benchmark_crossing <- map_df(benchmarks, function(bench) {
  crossing(
    Method = bench$methods,
    Metric = bench$metrics
  ) %>% mutate(
    Name = bench$name,
    n = 1
  )
}) %>%
  complete(Method, Metric, Name, fill = list(n = 0))

overlapdf <- benchmark_crossing %>%
  group_by(Method, Metric) %>%
  summarise(n = sum(n), .groups = "drop")

# overlap plot
g1 <- ggplot(overlapdf) +
  geom_tile(
    aes(
      Metric,
      forcats::fct_rev(Method),
      fill = factor(n)
    ),
    colour = "#CCCCCC",
    linewidth = 0.3
  ) +
  scale_fill_manual(values = palette) +
  scale_x_discrete(position = "top") +
  labs(fill = "# studies", x = "Used metrics", y = "Benchmarked methods") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 40, hjust = 0, size = 8),
    axis.ticks = element_blank(),
    panel.border = element_blank(),
    legend.position = "bottom"
  ) +
  coord_equal()

# timeline plot
dates <-
  bind_rows(
    method_info %>% mutate(type = "Method", event_type = "Publication") %>% rename(name = method),
    benchmark_commits %>%
      group_by(name = benchmark_name) %>%
      reframe(
        type = c("Benchmark", "Benchmark"),
        event_type = c("First commit", "Last commit"),
        date = as.Date(c(min(date), max(date)))
      ),
    map_df(
      benchmarks, function(ben) {
        as.tibble(ben$dates) %>%
          mutate(
            type = "Benchmark",
            event_type = name,
            name = ben$name,
            date = ymd(date)
          )
      })
  ) %>%
  mutate(
    date_dec = decimal_date(date),
    y = factor(
      ifelse(type == "Method", "Benchmarked\nmethods", name),
      levels = c("Benchmarked\nmethods", rev(names))
    ),
    event_type = factor(event_type, levels = c("First commit", "Preprint", "Publication", "Last commit"))
  )
method_dates <- dates %>% filter(type == "Method")
benchmark_dates <- dates %>% filter(type == "Benchmark")

yrs <- seq(2006, 2024)
g2 <- ggplot(dates, aes(date_dec, y)) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  geom_segment(
    aes(x = date_dec, xend = decimal_date(Sys.Date()), y = y, yend = y),
    method_dates %>% slice(which.min(date)),
    arrow = arrow(length = unit(0.3, "cm"), type = "closed")
  ) +
  geom_path(
    aes(x = date_dec, y = y),
    benchmark_dates %>% group_by(name) %>% slice(c(which.min(date), which.max(date)))
  ) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  ggbreak::scale_x_break(c(2006.5, 2015.5)) +
  labs(x = NULL, y = NULL, colour = "Event") +
  scale_x_continuous(
    limits = c(2006, 2026),
    breaks = yrs,
    labels = ifelse(yrs %% 2 == 0, sprintf("%4d", yrs), "")
  ) +
  theme_bw() +
  theme(
    axis.line.x = element_line(linewidth = ggplot2::rel(1), colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line.x.top = element_blank(),
    axis.ticks.x.top = element_blank(),
    axis.title.x.top = element_blank(),
    axis.text.x.top = element_blank(),
    axis.y.ticks = element_blank(),
    legend.position = "bottom"
  ) +
  scale_color_brewer(palette = "Set1")

# add tiles
df <- tibble(
  name = rev(names),
  xmin = 2024.5,
  xmax = 2026,
  ymin = seq_along(name) + .51,
  ymax = ymin + .98
)

g2_plus_tiles <- g2
for (i in seq_len(nrow(df))) {
  g2s <-
    ggplot(
      benchmark_crossing %>% filter(Name == df$name[[i]]),
      aes(
        Metric,
        forcats::fct_rev(Method),
        fill = factor(n)
      )
    ) +
    geom_rect(
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, x = NULL, y = NULL),
      data.frame(xmin = 0, xmax = length(metrics) + 1, ymin = 0, ymax = length(methods) + 1),
      fill = "#222222"
    ) +
    geom_raster() +
    scale_fill_manual(values = palette) +
    labs(x = NULL, y = NULL) +
    cowplot::theme_nothing() +
    coord_equal()
  g2_plus_tiles <- g2_plus_tiles + annotation_custom(
    grob = ggplotGrob(g2s),
    xmin = df$xmin[[i]],
    xmax = df$xmax[[i]],
    ymin = df$ymin[[i]],
    ymax = df$ymax[[i]]
  )
}

gc <- patchwork::wrap_plots(
  g1,
  # add a little bit of space at the top of the right plot
  g2_plus_tiles + expand_limits(y = 7),
  nrow = 1,
  widths = c(5, 6)
)
ggsave("figures/figure1/fig1a.pdf", gc, width = 12, height = 5)
ggsave("figures/figure1/fig1a.svg", gc, width = 12, height = 5)
ggsave("figures/figure1/fig1a.png", gc, width = 12, height = 5)
