library(tidyverse)
library(ggbeeswarm)
library(patchwork)

# data files are generated by running 'Rscript scripts/figure1a_generate_data.R'

# read data
benchmarks <- yaml::read_yaml("data/fig1a_benchmarks.yaml")
method_info <- as_tibble(yaml::read_yaml("data/fig1a_method_info.yaml")) %>%
  mutate(date = ymd(date))

benchmark_commits <- as_tibble(read.delim("data/fig1a_benchmark_commits.tsv", sep = "\t")) %>%
  mutate(date = ymd_hms(date))

# create data frames
methods <- sort(unique(unlist(map(benchmarks, "methods"))))
metrics <- sort(unique(unlist(map(benchmarks, "metrics"))))

benchmark_crossing <- map_df(benchmarks, function(bench) {
  crossing(
    Method = bench$methods,
    Metric = bench$metrics
  ) %>% mutate(
    Name = bench$name,
    n = 1
  )
}) %>%
  complete(Method, Metric, Name, fill = list(n = 0))

palette <- c("0" = "white", "1" = "#999999", "2" = "#222222")
overlapdf <- benchmark_crossing %>%
  group_by(Method, Metric) %>%
  summarise(n = sum(n), .groups = "drop")

g1 <- ggplot(overlapdf) +
  geom_tile(aes(Metric, forcats::fct_rev(Method), fill = factor(n)), colour = "#CCCCCC", linewidth = 0.5) +
  scale_fill_manual(values = palette) +
  labs(fill = "# overlap", x = "Metrics", y = "Methods") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  coord_equal()

g2 <- ggplot(benchmark_crossing) +
  geom_tile(aes(Metric, forcats::fct_rev(Method), fill = factor(n)), colour = "#CCCCCC", linewidth = 0.5) +
  scale_fill_manual(values = palette) +
  labs(x = "Metrics", y = "Methods") +
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), strip.background = element_blank(), legend.position = "none") +
  facet_wrap(~Name) +
  coord_equal()

g2f <- ggplot(benchmark_crossing) +
  geom_tile(aes(Metric, forcats::fct_rev(Method), fill = factor(n)), colour = "#CCCCCC", linewidth = 0.5) +
  scale_fill_manual(values = palette) +
  labs(x = "Metrics", y = "Methods") +
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), strip.background = element_blank(), legend.position = "none") +
  facet_wrap(~Name, nrow = 1) +
  coord_equal()

bc <- benchmark_commits %>%
  mutate(name = "Commit") %>%
  bind_rows(map_df(benchmarks, function(ben) as.tibble(ben$dates) %>% mutate(benchmark_name = ben$name, date = ymd(date)))) %>%
  mutate(swarm = name == "Commit" & !grepl("Mereu", benchmark_name))

g3 <- ggplot(bc) +
  geom_path(aes(date, benchmark_name), bc, linewidth = .5, alpha = .5) +
  ggbeeswarm::geom_quasirandom(aes(date, benchmark_name, colour = name, size = name), orientation = "y", bc %>% filter(swarm)) +
  geom_point(aes(date, benchmark_name, colour = name, size = name), bc %>% filter(!swarm)) +
  theme_classic() + 
  scale_colour_manual(values = c(Commit = "#555555", Preprint = "#66c2a5", Publication = "#8da0cb")) +
  scale_size_manual(values = c("Commit" = .25, Preprint = 3, Publication = 3)) +
  labs(colour = "Event type", size = "Event type", x = "Date", y = "Study")
ggsave("figures/figure1/fig1a_commits.pdf", g3, width = 7, height = 5)




dates <-
  bind_rows(
    method_info %>% mutate(type = "Method", event_type = "Publication") %>% rename(name = method),
    benchmark_commits %>%
      group_by(name = benchmark_name) %>%
      reframe(
        type = c("Benchmark", "Benchmark"),
        event_type = c("First commit", "Last commit"),
        date = as.Date(c(min(date), max(date)))
      ),
    map_df(
      benchmarks, function(ben) {
        as.tibble(ben$dates) %>%
          mutate(
            type = "Benchmark",
            event_type = name,
            name = ben$name,
            date = ymd(date)
          )
      })
  ) %>%
  mutate(
    date_dec = decimal_date(date),
    y = factor(ifelse(type == "Method", "Methods", name), levels = c("Methods", rev(sort(map_chr(benchmarks, "name"))))),
    event_type = factor(event_type, levels = c("First commit", "Preprint", "Publication", "Last commit"))
  )
method_dates <- dates %>% filter(type == "Method")
benchmark_dates <- dates %>% filter(type == "Benchmark")


g4 <- ggplot(dates, aes(date_dec, y)) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  geom_segment(
    aes(x = date_dec, xend = decimal_date(Sys.Date()), y = y, yend = y),
    method_dates %>% slice(which.min(date)),
    arrow = arrow(length = unit(0.3, "cm"), type = "closed")
  ) +
  geom_path(
    aes(x = date_dec, y = y),
    benchmark_dates %>% group_by(name) %>% slice(c(which.min(date), which.max(date)))
  ) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  ggbreak::scale_x_break(c(2007.5, 2015)) +
  theme_classic() +
  labs(x = "Time", colour = "Event") +
  scale_x_continuous(
    limits = c(2006, 2024),
    breaks = seq(2006, 2024),
    labels = sprintf("'%02d", seq(6, 24))
  ) +
  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x.top = element_blank(),
    axis.text.x.top = element_blank(),
    axis.line.x.top = element_blank(),
    axis.ticks.x.top = element_blank()
  ) +
  scale_color_brewer(palette = "Set1")

gc <- patchwork::wrap_plots(
  wrap_elements(full = g1),
  patchwork::wrap_plots(
    wrap_elements(full = g2f),
    # wrap_elements(full = g4),
    g4,
    ncol = 1
  ),
  nrow = 1,
  widths = c(5, 6)
)
ggsave("figures/figure1/fig1a.pdf", gc, width = 12, height = 5)
