library(tidyverse)
library(ggbeeswarm)
library(patchwork)
requireNamespace("ggbreak", quietly = TRUE)
requireNamespace("cowplot", quietly = TRUE)
requireNamespace("ggrepel", quietly = TRUE)
requireNamespace("forcats", quietly = TRUE)

# data files are generated by running 'Rscript scripts/figure1a_generate_data.R'

# read data
benchmarks <- yaml::read_yaml("data/fig1a_benchmarks.yaml")
method_info <- as_tibble(yaml::read_yaml("data/fig1a_method_info.yaml")) %>%
  mutate(date = ymd(date))
benchmark_commits <- as_tibble(read.delim("data/fig1a_benchmark_commits.tsv", sep = "\t")) %>%
  mutate(date = ymd_hms(date))

# create data frames
names <- sort(map_chr(benchmarks, "name"))
methods <- sort(unique(unlist(map(benchmarks, "methods"))))
metrics <- sort(unique(unlist(map(benchmarks, "metrics"))))
palette <- c("0" = "white", "1" = "#999999", "2" = "#222222")

benchmark_crossing <- map_df(benchmarks, function(bench) {
  crossing(
    Method = bench$methods,
    Metric = bench$metrics
  ) %>% mutate(
    Name = bench$name,
    n = 1
  )
}) %>%
  complete(Method, Metric, Name, fill = list(n = 0))

overlapdf <- benchmark_crossing %>%
  group_by(Method, Metric) %>%
  summarise(n = sum(n), .groups = "drop")

# overlap plot
g1 <- ggplot(overlapdf) +
  geom_tile(aes(Metric, forcats::fct_rev(Method), fill = factor(n)), colour = "#CCCCCC", linewidth = 0.5) +
  scale_fill_manual(values = palette) +
  scale_x_discrete(position = "top") +
  labs(fill = "# studies", x = "Metrics", y = "Methods") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 40, hjust = 0), legend.position = "bottom") +
  coord_equal()

# timeline plot
dates <-
  bind_rows(
    method_info %>% mutate(type = "Method", event_type = "Publication") %>% rename(name = method),
    benchmark_commits %>%
      group_by(name = benchmark_name) %>%
      reframe(
        type = c("Benchmark", "Benchmark"),
        event_type = c("First commit", "Last commit"),
        date = as.Date(c(min(date), max(date)))
      ),
    map_df(
      benchmarks, function(ben) {
        as.tibble(ben$dates) %>%
          mutate(
            type = "Benchmark",
            event_type = name,
            name = ben$name,
            date = ymd(date)
          )
      })
  ) %>%
  mutate(
    date_dec = decimal_date(date),
    y = factor(ifelse(type == "Method", "Methods", name), levels = c("Methods", rev(sort(map_chr(benchmarks, "name"))))),
    event_type = factor(event_type, levels = c("First commit", "Preprint", "Publication", "Last commit"))
  )
method_dates <- dates %>% filter(type == "Method")
benchmark_dates <- dates %>% filter(type == "Benchmark")

yrs <- seq(2006, 2024)
g2 <- ggplot(dates, aes(date_dec, y)) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  geom_segment(
    aes(x = date_dec, xend = decimal_date(Sys.Date()), y = y, yend = y),
    method_dates %>% slice(which.min(date)),
    arrow = arrow(length = unit(0.3, "cm"), type = "closed")
  ) +
  geom_path(
    aes(x = date_dec, y = y),
    benchmark_dates %>% group_by(name) %>% slice(c(which.min(date), which.max(date)))
  ) +
  geom_point(aes(date_dec, y, colour = event_type), dates) +
  ggbreak::scale_x_break(c(2006.75, 2015)) +
  theme_classic() +
  labs(x = NULL, colour = "Event") +
  scale_x_continuous(
    limits = c(2006, 2026),
    breaks = yrs,
    labels = ifelse(yrs %% 2 == 0, sprintf("%4d", yrs), "")
  ) +
  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x.top = element_blank(),
    axis.text.x.top = element_blank(),
    axis.line.x.top = element_blank(),
    axis.ticks.x.top = element_blank(),
    legend.position = "bottom"
  ) +
  scale_color_brewer(palette = "Set1")

# add tiles
df <- tibble(
  name = rev(names),
  xmin = 2024.5,
  xmax = 2026,
  ymin = seq_along(name) + .51,
  ymax = ymin + .98
)

g2_plus_tiles <- g2
for (i in seq_len(nrow(df))) {
  g2s <- ggplot(benchmark_crossing %>% filter(Name == df$name[[i]])) +
    geom_tile(
      aes(Metric, forcats::fct_rev(Method), fill = factor(n)),
      linewidth = 0.5
    ) +
    scale_fill_manual(values = palette) +
    labs(x = NULL, y = NULL) +
    cowplot::theme_nothing() +
    theme(plot.background = element_rect(fill = NA, colour = "#222222")) +
    coord_equal()
  g2_plus_tiles <- g2_plus_tiles + annotation_custom(
    grob = ggplotGrob(g2s),
    xmin = df$xmin[[i]],
    xmax = df$xmax[[i]],
    ymin = df$ymin[[i]],
    ymax = df$ymax[[i]]
  )
}

gc <- patchwork::wrap_plots(
  wrap_elements(full = g1),
  patchwork::wrap_plots(
    patchwork::plot_spacer(),
    g2_plus_tiles,
    ncol = 1,
    heights = c(1, 4)
  ),
  nrow = 1,
  widths = c(5, 6)
)
ggsave("figures/figure1/fig1a.pdf", gc, width = 12, height = 5)
ggsave("figures/figure1/fig1a.png", gc, width = 12, height = 5)
